name: founderslink
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  material_floating_search_bar: 
  custom_bottom_navigation_bar: ^0.0.1
  curved_navigation_bar: ^0.3.0
  http: ^0.12.2
  shared_preferences: ^0.5.10
  agora_rtc_engine: ^3.2.1
  permission_handler: ^5.0.0
  pull_to_refresh: ^1.6.4
  flutter_boom_menu: ^1.0.2
  flutter_speed_dial: ^1.2.1
  syncfusion_flutter_sliders: ^18.1.42-beta

  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  

  agora_rtm: ^0.9.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logoFounder.png
    - assets/images/slider.png
    - assets/images/check2021.png
    - assets/images/founder.png
    - assets/images/graduate.png
    - assets/images/people.png
    - assets/images/gentle.png
    - assets/images/whiteppl.png
    - assets/images/whiteB.png
    - assets/images/statistic.png
    - assets/images/tie.png
    - assets/images/whitefounder.png
    - assets/images/indian.png
    - assets/images/logoIcon.png
    - assets/images/girl1.png
    - assets/images/girl2.png
    - assets/images/boy1.png
    - assets/images/boy2.png
    - assets/images/resource.png
    - assets/images/user.png
    - assets/images/Message.png
    - assets/images/database.png
    - assets/images/BG.png
    - assets/images/colorado.png
    - assets/images/firstTime.png
    - assets/images/sarah.png
    - assets/images/tiffany.png
    - assets/images/private.png
    - assets/images/theteam.png
    - assets/images/Fred.png
    - assets/images/Alice.png
    - assets/images/James.png
    - assets/images/word.png
    - assets/images/pdf.png
    - assets/images/excel.png
    - assets/images/Tallfred.png
    - assets/images/Talljames.png
    - assets/images/Talltiffany.png
    - assets/images/Tallalice.png
    - assets/images/founderlink.png
    - assets/images/menu.png
    - assets/images/recruit.png
    - assets/images/pitch.png
    - assets/images/saza.png
    - assets/images/shake.png
    - assets/images/beta.png
    - assets/images/myPitch.png
    - assets/images/peopleadd.png
    - assets/images/jasmine.png
    - assets/images/green.png
    - assets/images/logocircle.png
    - assets/images/arrowUp.png
    - assets/images/floating.png
    - assets/images/group.png
    - assets/images/anonymous.png
    - assets/images/blackvs.png
    - assets/images/profile.png
    - assets/images/womenfounders.png
    - assets/images/logout.png





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
